adminapp/urls.py
from django.urls import path

from adminapp.views import users, categories, products

app_name = 'adminapp'

urlpatterns = [
    # users (create, read, update, delete)
    path('users/index', users.index, name='users'),
    path('users/create/', users.create, name='user_create'),  # admin:user_create
    path('users/read/<int:id>', users.read, name='user_read'),
    path('users/update/<int:id>', users.update, name='user_update'),
    path('users/delete/<int:id>', users.delete, name='user_delete'),

    # categories (CRUD)
    path('categories/index', categories.index, name='categories'),
    path('categories/create/', categories.create, name='category_create'),
    path('categories/read/<int:id>', categories.read, name='category_read'),
    path('categories/update/<int:id>', categories.update, name='category_update'),
    path('categories/delete/<int:id>', categories.delete, name='category_delete'),

    # products (CRUD, list_by_category)
    path('products/create/', products.create, name='product_create'),
    path('products/read/<int:id>', products.read, name='product_read'),
    path('products/list/<int:category>', products.list_by_category, name='product_category'),
    path('products/update/<int:id>', products.update, name='product_update'),
    path('products/delete/<int:id>', products.delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
from django.urls import re_path
import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),

    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit')
    ]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

import mainapp.views as controller

urlpatterns = [
    path('', controller.main, name='main'),
    path('contact/', controller.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),

    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', include('adminapp.urls', namespace='admin')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

mainapp/urls.py
from django.urls import path

import mainapp.views as controller

app_name = 'mainapp'

urlpatterns = [
    path('', controller.products, name='index'),  # {% url 'products:index' %}
    path('<int:id>/', controller.products, name='category'),  # products:category id=1
    path('details/<int:id>/', controller.product_detail, name='details'),  # products:details id=1
]

mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from basketapp.models import Basket

import datetime
from .models import ProductCategory, Product


def get_current_basket(current_user):
    if current_user.is_authenticated:
        items = Basket.objects.filter(user=current_user)
    else:
        items = None

    return items


def main(request: HttpRequest):
    title = 'главная'

    products = Product.objects.all()

    return render(request, 'mainapp/index.html', {
        'title': title,
        'products': products,
        'basket': get_current_basket(request.user)
    })


def products(request: HttpRequest, id=None):
    title = 'продукты'
    links_menu = ProductCategory.objects.all()

    if id is not None:
        same_products = Product.objects.filter(category__pk=id)
    else:
        same_products = Product.objects.all()

    return render(request, 'mainapp/products.html', {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'basket': get_current_basket(request.user)
    })


def product_detail(request: HttpRequest, id=None):
    # if id is not None:
    # item = Product.objects.get(pk=id)
    item = get_object_or_404(Product, pk=id)
    same_products = Product.objects.exclude(pk=id).filter(category__pk=item.category_id)
    links_menu = ProductCategory.objects.all()

    context = {
        'title': f'Товар: {item.name}',
        'item': item,
        'products': same_products,
        'links_menu': links_menu,
        'basket': get_current_basket(request.user)
    }

    return render(request, 'mainapp/details.html', context)


def contact(request: HttpRequest):
    title = 'о нас'
    visit_date = datetime.datetime.now()
    locations = [
        {
            'city': 'Москва',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Екатеринбург',
            'phone': '+7-777-777-7777',
            'email': 'info_yekaterinburg@geekshop.ru',
            'address': 'Близко к центру',
        },
        {
            'city': 'Владивосток',
            'phone': '+7-999-999-9999',
            'email': 'info_vladivostok@geekshop.ru',
            'address': 'Близко к океану',
        },
    ]

    return render(request, 'mainapp/contact.html', {
        'title': title,
        'visit_date': visit_date,
        'locations': locations
    })

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:index' %}">
            все
        </a>
    </li>

    {% for link in links_menu %}
        <li>
            <a href="/products/{{ link.id }}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
<ul class="menu">
    <li>
        <a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}"
           class="{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category' or request.resolver_match.url_name == 'index' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a>
    </li>

    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                Мой профиль
            </a>
        </li>
    {% endif %}

    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin:categories' %}">
                Админ-панель
            </a>
        </li>
    {% endif %}

    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">
                выйти
            </a>
        {% else %}
            <a href="{% url 'auth:login' %}">
                войти
            </a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:index' %}" class="basket">
    <span>
        {% if basket %}
            {{ basket.0.total_quantity }} товаров <br>
            {{ basket.0.total_cost }} руб <br>
        {% endif %}
    </span>
</a>