authapp/urls.py
from django.urls import path
from django.urls import re_path
import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),

    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit')
    ]

basketapp/urls.py
from django.urls import path

import basketapp.views as controller

app_name = 'basketapp'

urlpatterns = [
    path('', controller.index, name='index'),
    path('add/<int:id>/', controller.add, name='add'),
    path('remove/<int:id>/', controller.remove, name='remove'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

import mainapp.views as controller

urlpatterns = [
    path('', controller.main, name='main'),
    path('contact/', controller.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),

    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', include('adminapp.urls', namespace='admin')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

mainapp/urls.py
from django.urls import path

import mainapp.views as controller

app_name = 'mainapp'

urlpatterns = [
    path('', controller.products, name='index'),  # {% url 'products:index' %}
    path('<int:id>/', controller.products, name='category'),  # products:category id=1
    path('details/<int:id>/', controller.product_detail, name='details'),  # products:details id=1
]

mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

adminapp/views/products.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def create(request: HttpRequest):
    return HttpResponse('action -> create')


def read(request: HttpRequest, id):
    return HttpResponse('action -> read')


def list_by_category(request: HttpRequest, category):
    return HttpResponse('action -> list')


def update(request: HttpRequest, id):
    return HttpResponse('action -> update')


def delete(request: HttpRequest, id):
    return HttpResponse('action -> delete')

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from basketapp.models import Basket

import datetime
from .models import ProductCategory, Product


def get_current_basket(current_user):
    if current_user.is_authenticated:
        items = Basket.objects.filter(user=current_user)
    else:
        items = None

    return items


def main(request: HttpRequest):
    title = 'главная'

    products = Product.objects.all()

    return render(request, 'mainapp/index.html', {
        'title': title,
        'products': products,
        'basket': get_current_basket(request.user)
    })


def products(request: HttpRequest, id=None):
    title = 'продукты'
    links_menu = ProductCategory.objects.all()

    if id is not None:
        same_products = Product.objects.filter(category__pk=id)
    else:
        same_products = Product.objects.all()

    return render(request, 'mainapp/products.html', {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'basket': get_current_basket(request.user)
    })


def product_detail(request: HttpRequest, id=None):
    # if id is not None:
    # item = Product.objects.get(pk=id)
    item = get_object_or_404(Product, pk=id)
    same_products = Product.objects.exclude(pk=id).filter(category__pk=item.category_id)
    links_menu = ProductCategory.objects.all()

    context = {
        'title': f'Товар: {item.name}',
        'item': item,
        'products': same_products,
        'links_menu': links_menu,
        'basket': get_current_basket(request.user)
    }

    return render(request, 'mainapp/details.html', context)


def contact(request: HttpRequest):
    title = 'о нас'
    visit_date = datetime.datetime.now()
    locations = [
        {
            'city': 'Москва',
            'phone': '+7-888-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Екатеринбург',
            'phone': '+7-777-777-7777',
            'email': 'info_yekaterinburg@geekshop.ru',
            'address': 'Близко к центру',
        },
        {
            'city': 'Владивосток',
            'phone': '+7-999-999-9999',
            'email': 'info_vladivostok@geekshop.ru',
            'address': 'Близко к океану',
        },
    ]

    return render(request, 'mainapp/contact.html', {
        'title': title,
        'visit_date': visit_date,
        'locations': locations
    })

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block menu %}
        <div class="hero-white">
            <div class="header clearfix">
                {% include 'mainapp/includes/inc_menu.html' %}
            </div>
        </div>
    {% endblock %}
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>

</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/basket.js' %}"></script>
{% endblock %}

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static%}

{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock %}

{% block content %}
    <div class="location">
        {% for location in locations %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ location.city }}</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ location.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ location.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ location.address }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/details.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ MEDIA_URL }}{{ item.image }}">
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ item.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ item.price }} <span>руб</span></p>

{#                {% if request.user.is_authenticated %}#}
                <a href="{% url 'basket:add' id=item.id %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
{#                {% endif %}#}

                <div class="description-text">
                    <p>{{ item.description }}</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="{% url 'products:index' %}">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">

                {% for product in products %}
                    <div class="block">
                        <a href="#"><img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h3>Категория:{{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }} </p>
                                <p>Цена: {{ product.price }} </p>
                                <p>На складе: {{ product.quantity }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}


{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:details' id=product.id %}"><img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h3>Категория:{{ product.category.name }}</h3>
                            <h4>Название: {{ product.name }}</h4>
                            <p>Описание: {{ product.description }} </p>
                            <p>Цена: {{ product.price }} </p>
                            <p>На складе: {{ product.quantity }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Каталог</h2>
            </div>
            <div class="related-products clearfix">

                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:details' id=product.id %}">
                            <img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h3>Категория:{{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }} </p>
                                <p>Цена: {{ product.price }} </p>
                                <p>На складе: {{ product.quantity }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}